language: go

go: 1.11.5

env:
  global:
    - ETCD_VER=v3.3.0
    - GO111MODULE=on
    - DOCKER_LATEST=latest

matrix:
  exclude:
    go: 1.11.5

setup_etcd: &setup_etcd
  before_script:
    - curl -L https://github.com/coreos/etcd/releases/download/${ETCD_VER}/etcd-${ETCD_VER}-linux-amd64.tar.gz -o /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz
    - mkdir -p /tmp/etcd
    - tar xzvf /tmp/etcd-${ETCD_VER}-linux-amd64.tar.gz -C /tmp/etcd --strip-components=1
    - /tmp/etcd/etcd --advertise-client-urls http://127.0.0.1:12379 --listen-client-urls http://127.0.0.1:12379 > /dev/null &

build_docker_image: &build_docker_image
  before_script:
    - |
      docker-compose build dev_weaver
      [ ! -z $TRAVIS_TAG ] && docker tag weaver_dev_weaver:$DOCKER_LATEST gojektech/weaver:$TRAVIS_TAG
      [ ! -z $TRAVIS_TAG ] && docker tag gojektech/weaver:$TRAVIS_TAG gojektech/weaver:$DOCKER_LATEST
      docker images

services:
  - docker

stages:
  - test
  - name: deploy
    if: (repo == gojektech/weaver) AND (branch == master) AND (tag IS present)

# travis is stupid to do its own custom install and script things
# This is the only way to skip them from running
before_script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
install: echo "Skip global installing..."
script: echo "Skip global script..."

jobs:
  include:
    - stage: test
    - name: "Make Spec"
      <<: *setup_etcd
      script: make test
    - name: "Docker Spec"
      <<: *build_docker_image
      script: make docker-spec
      after_script: make docker-clean

    - stage: deploy
    - name: "Release Builds"
      script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist --skip-validate
    - name: "Docker Builds"
      <<: *build_docker_image
      script: docker push gojektech/weaver:$TRAVIS_TAG && docker push gojektech/weaver:$DOCKER_LATEST

notifications:
  email: false

